version: '2'
services:
    wedding-nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        image: wedding/nginx
        links:
            - wedding-php
        volumes:
            - ./public:/var/www/code/public
        networks:
            - web

    wedding-php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/var/www/code
        networks:
            - web

networks:
    web:
        external:
            name: karrleinbase_webgateway
